version: '3.8'

services:
  #database section
  onlineshopdb:
    image: postgres:alpine3.16
  
  basketdb:
    image: redis:alpine
  
  inventorydb:
    image: mongo
  
  # infrastructure section
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  pgadmin:
    image: dpage/pgadmin4
  
  portainer:
    image: portainer/portainer-ce
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2

#network section
networks:
  default:
    name: ecommerce_microservice
    driver: bridge

#volumes section
volumes:
  postgres_data:
    name: postgres_data
  
  portainer_data:
    name: portainer_data
  
  elasticsearch_data:
    name: elasticsearch_data
  
  jaeger_data:
    name: jaeger_data
  
  mongo_data:
    name: mongo_data
  
  pgadmin_data:
    name: pgadmin_data
  